## webserver
server:
  port: 9090
  servlet:
    contextPath: /api


spring:
  ## JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  ## Flyway
  flyway:
    schemas: cookbook
  # File uploads
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 15MB
  jackson:
    default-property-inclusion: non_null

file:
  storage:
    location: ./uploads

logging:
  pattern.console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

---
spring:
  ## JPA
  jpa:
    properties:
      hibernate:
        show-sql: true
  ## MySQL
  datasource:
    url: jdbc:mysql://localhost:9876/cookbook
    username: cookbook
    password: ${db.password}
  ## Flyway
  flyway:
    url: jdbc:mysql://localhost:9876/cookbook
    user: cookbook
    password: ${db.password}
  config:
    activate:
      on-profile: local

logging:
  level:
    com.ractoc: DEBUG

---
spring:
  ## JPA
  jpa:
    properties:
      hibernate:
        show-sql: false
  ## MySQL
  datasource:
    url: jdbc:mysql://192.168.1.195:3306/cookbook
    username: cookbook
    password: ${db.password}
  ## Flyway
  flyway:
    url: jdbc:mysql://192.168.1.195:3306/cookbook
    user: cookbook
    password: ${db.password}
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.ractoc: DEBUG
---